version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: opusscript
    versions:
    - 0.0.7
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
